<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1514076508069' stop='1514076515954'>
    <name>Testing the report and log</name>
    <title>Testing the report and log</title>
    <test-cases>
        <test-case start='1514076508070' status='passed' stop='1514076513179'>
            <name>validating correct title</name>
            <title>validating correct title</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='7d53a825-57d0-4724-a9f6-39cd7bdac15b-attachment.png' type='image/png' size='38136'/>
            </attachments>
        </test-case>
        <test-case start='1514076513179' status='failed' stop='1514076515953'>
            <name>validating in-correct title</name>
            <title>validating in-correct title</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='1f2d6380-d017-4e61-9845-7ec3c0572970-attachment.png' type='image/png' size='38136'/>
            </attachments>
            <failure>
                <message>Expected 'Protractor practice website - Banking App' to contain 'ProtractorOne'.</message>
                <stack-trace>Error: Failed expectation
                    at UserContext.&lt;anonymous> (/Users/suyashnande/WebstormProjects/Protractor_Test/validate_spec.js:20:23)
                    at /usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:112:25
                    at new ManagedPromise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1077:7)
                    at ControlFlow.promise (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2505:12)
                    at schedulerExecute (/usr/local/lib/node_modules/protractor/node_modules/jasminewd2/index.js:95:18)
                    at TaskQueue.execute_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3084:14)
                    at TaskQueue.executeNext_ (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:3067:27)
                    at asyncRun (/usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2974:25)
                    at /usr/local/lib/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:668:7</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>